services:

  emailflare:
    container_name: emailflare
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_USE_ENV_PROXY=1
    volumes:
      - /docker/config/emailflare:/data
    networks:
      - proxy
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost/health" ]
      start_period: 15s

networks:
  proxy:
    external: true
