/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InboxSettingsRouteImport } from './routes/inbox/settings'
import { Route as InboxSequencesRouteImport } from './routes/inbox/sequences'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxSettingsRoute = InboxSettingsRouteImport.update({
  id: '/inbox/settings',
  path: '/inbox/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxSequencesRoute = InboxSequencesRouteImport.update({
  id: '/inbox/sequences',
  path: '/inbox/sequences',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRoute
  '/inbox/sequences': typeof InboxSequencesRoute
  '/inbox/settings': typeof InboxSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/users': typeof SettingsUsersRoute
  '/inbox/': typeof InboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRoute
  '/inbox/sequences': typeof InboxSequencesRoute
  '/inbox/settings': typeof InboxSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/users': typeof SettingsUsersRoute
  '/inbox': typeof InboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRoute
  '/inbox/sequences': typeof InboxSequencesRoute
  '/inbox/settings': typeof InboxSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/users': typeof SettingsUsersRoute
  '/inbox/': typeof InboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domains'
    | '/keys'
    | '/login'
    | '/logs'
    | '/playground'
    | '/setup'
    | '/templates'
    | '/inbox/sequences'
    | '/inbox/settings'
    | '/invite/$token'
    | '/settings/users'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/domains'
    | '/keys'
    | '/login'
    | '/logs'
    | '/playground'
    | '/setup'
    | '/templates'
    | '/inbox/sequences'
    | '/inbox/settings'
    | '/invite/$token'
    | '/settings/users'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/domains'
    | '/keys'
    | '/login'
    | '/logs'
    | '/playground'
    | '/setup'
    | '/templates'
    | '/inbox/sequences'
    | '/inbox/settings'
    | '/invite/$token'
    | '/settings/users'
    | '/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainsRoute: typeof DomainsRoute
  KeysRoute: typeof KeysRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SetupRoute: typeof SetupRoute
  TemplatesRoute: typeof TemplatesRoute
  InboxSequencesRoute: typeof InboxSequencesRoute
  InboxSettingsRoute: typeof InboxSettingsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/settings': {
      id: '/inbox/settings'
      path: '/inbox/settings'
      fullPath: '/inbox/settings'
      preLoaderRoute: typeof InboxSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/sequences': {
      id: '/inbox/sequences'
      path: '/inbox/sequences'
      fullPath: '/inbox/sequences'
      preLoaderRoute: typeof InboxSequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainsRoute: DomainsRoute,
  KeysRoute: KeysRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  PlaygroundRoute: PlaygroundRoute,
  SetupRoute: SetupRoute,
  TemplatesRoute: TemplatesRoute,
  InboxSequencesRoute: InboxSequencesRoute,
  InboxSettingsRoute: InboxSettingsRoute,
  InviteTokenRoute: InviteTokenRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  InboxIndexRoute: InboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
